all:
	gcc main.c -o main -m32 -std=c99 -lpthread -O3
	./main
	gcc main.c -o main -m32 -std=c99 -lpthread -O2
	./main
	gcc main.c -o main -m32 -std=c99 -lpthread -O1
	./main
	gcc main.c -o main -m32 -std=c99 -lpthread -O0
	./main

